development:
  adapter: mysql
  database: dienhwa_dev
  username: root
  password: 24048mic
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

test:
  adapter: mysql
  database: dienhwa_test
  username: root
  password: 24048mic
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

