class AddIndexes < ActiveRecord::Migration
  def self.up
    add_index 'results', 'company_id'
    add_index 'jobs', 'user_id'
    add_index 'jobs', 'job_type_id'
    add_index 'jobs', 'employee_id'
    add_index 'jobs', 'customer_id'
    add_index 'jobs', 'result_id'
    add_index 'jobs', 'zone_id'
    add_index 'jobs', 'serial_id'
    add_index 'jobs', 'phone_id'
    add_index 'jobs', 'reason_id'
    add_index 'jobs', 'company_id'
    add_index 'job_types', 'company_id'
    add_index 'action_logs', 'session_id'
    add_index 'action_logs', 'user_id'
    add_index 'action_logs', 'company_id'
    add_index 'employees', 'company_id'
    add_index 'users', 'role_id'
    add_index 'users', 'company_id'
    add_index 'zones', 'company_id'
  end

  def self.down
    remove_index 'results', 'company_id'
    remove_index 'jobs', 'user_id'
    remove_index 'jobs', 'job_type_id'
    remove_index 'jobs', 'employee_id'
    remove_index 'jobs', 'customer_id'
    remove_index 'jobs', 'result_id'
    remove_index 'jobs', 'zone_id'
    remove_index 'jobs', 'serial_id'
    remove_index 'jobs', 'phone_id'
    remove_index 'jobs', 'reason_id'
    remove_index 'jobs', 'company_id'
    remove_index 'job_types', 'company_id'
    remove_index 'action_logs', 'session_id'
    remove_index 'action_logs', 'user_id'
    remove_index 'action_logs', 'company_id'
    remove_index 'employees', 'company_id'
    remove_index 'users', 'role_id'
    remove_index 'users', 'company_id'
    remove_index 'zones', 'company_id'
  end
end
